import { NoSqlClient } from "@db/nosql.client";
import { Model } from "@models/model";
import { IError, ErrorTypes, isError } from "@lib/error.interface";
import { Datastore, Query } from "@google-cloud/datastore";
import { API_URL } from "@routes/routes.main";
import { Formats } from "@lib/formats.interface";

// TODO: implement ship interface
//      { "id":"abc123", #this should be automatically generated by your API and should probably be a string
//      "name": "Sea Witch", #The name of the ship, a string
//      "type":"Catamaran", #The type of ship, power boat, sailboat, catamaran etc. a string
//      "length":28, #The length of the ship
//      "owner": "Alice", #The identifier of the owner of the ship
//      "self":"https://appspot.com/ships/abc123" #The link to the ship
//      }

/**
 * interface used for constructing and inserting ship objects into the datastore
 *  (validates post requests)
 * @property id     unique identifier. Not supplied by client
 * @property name   ship name (must be unique)   
 * @property type   ship type 
 * @property length ship length
 * @property self   a live link to the ship object
 */
export interface IShipPrototype {
    id?: string,
    name: string,       
    type: string,       
    length: number     
    self?: string
}

/**
 * interface used to validate ship objects retrieved from the datastore
 */
export interface IShipResult {
    id: string,        
    name: string,
    type: string,
    length: number,
    self: string
}

export const SHIPS = "ships";

/**
 * manages construction, editing, and deletion of ship objects in 
 *  the google-cloud datastore
 */
export class ShipsModel extends Model {
    /**
     * singleton
     */
    private static _instance: ShipsModel;
    public static get Instance(): ShipsModel {
        if (!this._instance) this._instance = new ShipsModel();
        return this._instance;
    }

    protected nosqlClient: NoSqlClient;

    private constructor() { 
        super();        
        this.nosqlClient = NoSqlClient.Instance;
        
        console.log("ShipsModel initialized");
    }

    /** check that name supplied in request is unique */
    public async nameUnique(_testName: string): Promise<boolean> {
        /** get all names */
        let allShips = await this.getAllShips() as IShipResult[];
        if (!isError(allShips)) {
            /** check against each name */
            for (let ship of allShips) 
                if (_testName == ship.name) 
                    return false;
        }
        /** name is unique */
        return true;
    }

    /**
     * determine if an object conforms to the Iship interface
     */
    public confirmInterface(obj: any): boolean {
        // TODO: 
        return;
    }

    /** 
     * confirm that ship with id exists 
     */
    public async shipExistsById(_id: string): Promise<boolean> {
        let result = await this.getShipById(_id) as IShipResult;
        if (isError(result)) return false;
        return true;
    }


    /**
     * retrieve a ship object by its datastore id
     */
    public async getShipById(shipId: string, format: string = Formats.JSON)
        : Promise<IShipResult | string | IError> {
        // TODO:
        return
    }

    /**
     * retrieve entire collection (all SHIPS)
     */
    public async getAllShips(): Promise<IShipResult[] | IError> {
        let allShips = await this.nosqlClient.datastoreGetCollection(SHIPS);
        if (allShips == undefined) return <IError>{ error_type: ErrorTypes.NOT_FOUND }
        return allShips;
    }

    /**
     * create a new ship object in the datastore
     */
    public async createShip(_name: string, _type: string, _length: number)
        : Promise<string | IError> {
        // TODO:
        return
    }

    /**
     * delete a ship from datastore
     */
    public async deleteShip(shipId: string): Promise<any> {
        return this.nosqlClient.datastoreDelete(SHIPS, shipId)
            .then(() => {
                for (let deleteCallback of this.deleteCallbacks)
                    deleteCallback(shipId);
            });
    }
}