
import { Datastore } from "@google-cloud/datastore";
import { NoSqlClient } from "@db/nosql.client";

export interface ISlip {
    /** id: string, */      // autogenerated
    number: number,         // slip number (human readable unique identifier)
    current_boat: string,   // id of current boat, null if empty
    arrival_date: string,   // date the current boat arrived
}

export class SlipsModel {
    private nosqlClient: NoSqlClient;

    constructor() { 
        this.nosqlClient = NoSqlClient.Instance;
        console.log("SlipsModel initialized");
    }

    public async getSlip() {

    }

    public async createSlip(data) {

    }

    public async deleteSlip() {

    }

    public async editSlip() {

    }
}
