import { NoSqlClient } from "@db/nosql.client";
import { Model } from "@models/model";
import { IError, ErrorTypes } from "@lib/error.interface";
import { isError } from "util";
import { IBoatResult, BoatsModel, BOATS } from "@models/boats.model";
import { Query } from "@google-cloud/datastore";
import { API_URL } from "@routes/routes.main";

export interface ISlipPrototype {
    id?: string,            // autogenerated, added in createSlip()
    number: number,         // human readable unique identifier, supplied in POST request
    current_boat?: string,  // id of current boat, null if empty
    arrival_date?: string,  // date the current boat arrived
    self?: string,          // added in createSlip()
    boat_link?: string      // added in createSlip()
}

export interface ISlipResult {
    id: string,
    number: number,
    current_boat: string,
    arrival_date: string,
    self: string
    boat_link: string
}

export const SLIPS = "slips";

export class SlipsModel extends Model {
    private static _instance: SlipsModel;
    public static get Instance(): SlipsModel {
        if (!this._instance) this._instance = new SlipsModel();
        return this._instance;
    }

    protected nosqlClient: NoSqlClient;
    private boatsModelRef: BoatsModel;

    constructor() { 
        super();
        this.nosqlClient = NoSqlClient.Instance;

        this.boatsModelRef = BoatsModel.Instance;
        this.boatsModelRef.registerDeleteCallback(this.handleBoatDeleted)

        console.log("SlipsModel initialized");
    }

    public async numberUnique(_testNumber: number): Promise<boolean> {
        /** get all numbers */
        let allSlips = await this.getAllSlips() as ISlipResult[];
        if (!isError(allSlips)) {
            /** check against each number */
            for (let slip of allSlips) 
                if (_testNumber == slip.number) 
                    return false;
        }
        /** number is unique */
        return true;
    }

    public confirmInterface(obj: any): boolean {
        /** only number will be supplied when creating a new slip */
        if (!("number" in obj) || !(typeof obj.number == "number")) {
            return false;
        } else return true;
    }

    public async slipExistsById(_id: string): Promise<boolean> {
        let result = await this.getSlipById(_id);
        if (isError(result)) return false;
        return true;
    }

    public async getSlipById(slipId: string): Promise<ISlipResult | IError> {
        let slip = await this.nosqlClient.datastoreGetById(SLIPS, slipId);
        if (slip == undefined) return <IError>{ error_type: ErrorTypes.NOT_FOUND }
        return slip;
    }

    public async getAllSlips(): Promise<ISlipResult[] | IError> {
        let allSlips = await this.nosqlClient.datastoreGetCollection(SLIPS);
        if (allSlips == undefined) return <IError>{ error_type: ErrorTypes.NOT_FOUND }
        return allSlips
    }

    public async createSlip(_number: number): Promise<any> {
        const newData: ISlipPrototype = {
            number: _number,
            current_boat: null,
            arrival_date: null      
        }

        let newKey = await this.nosqlClient.datastoreSave(SLIPS, newData);

        /** 
         * create live link and update entity in datastore
         */
        Object.assign(newData, { id: `${newKey.id}` });
        Object.assign(newData, { self: `${API_URL}/${SLIPS}/${newKey.id}` })

        const newSlip = {
            key: newKey,
            data: newData
        }

        /**
         * update with live link and id
         */
        await this.nosqlClient.datastoreUpsert(newSlip);

        return newKey;
    }

    public async deleteSlip(slipId: string): Promise<any> {
        let deleted = await this.nosqlClient.datastoreDelete(SLIPS, slipId);
        return deleted;
    }

    public async editSlip(slipId: string, editSlip: Partial<ISlipPrototype>) {
        if (await this.slipExistsById(slipId)) {
            let edited = await this.nosqlClient.datastoreEdit(SLIPS, slipId, editSlip);
            return edited;
        } else return <IError>{ error_type: ErrorTypes.NOT_FOUND }
    }

    public async dockBoatAtSlip(slipId: string, boatId: string)
        : Promise<any | IError> {
        const date: string = (new Date).toString();

        /**
         * check if boat is docked somewhere else
         * check if slip is occupied
         */
        let allSlips = await this.getAllSlips();
        if (!isError(allSlips)) {
            let slipExists = false, boatDockedElsewhere = false, slipOccupied = false;
            let dockedAtSlip = null;
            for (let _slip of (allSlips as ISlipResult[])) {
                if (_slip.id == slipId) {
                    slipExists = true;
                    if (_slip.current_boat != null && _slip.current_boat != boatId) {
                        return <IError>{ error_type: ErrorTypes.FORBIDDEN }
                    }
                } else if (_slip.current_boat == boatId) {
                    boatDockedElsewhere = true;
                    dockedAtSlip = _slip.id;
                }
            }
            if (!slipExists) return <IError>{ error_type: ErrorTypes.NOT_FOUND }
            if (boatDockedElsewhere) {
                await this.evacuateSlip(dockedAtSlip);
            }
            let docked = await this.editSlip(slipId, {
                current_boat: boatId,
                arrival_date: date,
                boat_link: `${API_URL}/${BOATS}/${boatId}`
            });        
            
            return docked;
        } else return <IError>{ error_type: ErrorTypes.NOT_FOUND }
    }

    public async evacuateFromSlip(slipId: string, boatId: string)
        : Promise<any | IError> {
        let slip = await this.getSlipById(slipId) as ISlipResult;
        if (!isError(slip)) {
            let boat = await this.boatsModelRef.getBoatById(boatId) as IBoatResult;
            if (!isError(boat) && (slip.current_boat == boat.id)) {
                let evacuated = await this.evacuateSlip(slipId);
                return evacuated;
            }
        }
        return <IError>{ error_type: ErrorTypes.NOT_FOUND }
    }

    private async evacuateSlip(slipId: string): Promise<any> {
        let edited = this.editSlip(slipId, {
            current_boat: null
        });
        return edited;
    }

    private async handleBoatDeleted(boatId: string): Promise<any | IError> {
        let allSlips = await this.getAllSlips() as ISlipResult[];
        if (!isError(allSlips)) {
            for (let slip of allSlips) {
                if (slip.current_boat == boatId) {
                    let slipId = await this.nosqlClient.getIdFromData(slip)
                    let evacuated = await this.evacuateSlip(slipId);
                    return evacuated;
                }
            }
        } else {
            let error = allSlips; 
            return allSlips;
        }
    }
}
